config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: "pages#about"
  resources :members
  resources :events

  get 'pages/about', to: 'pages#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  # Some setup you must do manually if you haven't yet:

  #   Ensure you have overridden routes for generated controllers in your routes.rb.
  #   For example:

  #     Rails.application.routes.draw do
  #       devise_for :users, controllers: {
  #         sessions: 'users/sessions'
  #       }
  #     end

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  has_and_belongs_to_many :members
  validates :description, presence: true
  validates :event_date, presence: true
  validates :event_location, presence: true

  def start_time
    event_date # #Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
  end
end

app/models/events_members.rb
# frozen_string_literal: true

class EventsMembers < ApplicationRecord
  belongs_to :event
  belongs_to :member
end

app/models/member.rb
# frozen_string_literal: true

class Member < ApplicationRecord
  has_and_belongs_to_many :events
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone, presence: true
  validates :phone, numericality: { only_integer: true }
  validates :phone, length: { is: 10 }
  validates :birthday, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

  def date_convert
    strftime('%m-%d')
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :new_user_email
  def new_user_email 
    UserMailer.with(user: self).new_user_email.deliver_now
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def after_sign_in_path_for(_resource)
    events_path # your path
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found
  before_action :set_event, only: %i[show edit update destroy]
  layout 'event_layout'

  # GET /events
  # GET /events.json
  def index
    # @events = Event.all
    # Scope your query to the dates being shown:
    start_date = params.fetch(:event_date, Date.today).to_date
    @events = Event.where(event_date: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @members = @event.members.all
  end

  # GET /event/new
  def new
    @event = Event.new
  end

  # GET /event/:id/edit
  def edit; end

  # POST /event
  # POST /event.json
  def create
    @event = Event.new(event_params)
    if @event.save
      flash.notice = 'The event record was created successfully.'
      redirect_to @event
    else
      flash.now.alert = @event.errors.full_messages.to_sentence
      render :new
    end
  end

  # PATCH/PUT /events/id
  # PATCH/PUT /events/1.json
  def update
    if @event.update(event_params)
      flash.notice = 'The event record was updated successfully.'
      redirect_to @event
    else
      flash.now.alert = @event.errors.full_messages.to_sentence
      render :edit
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:description, :event_date, :event_location, member_ids: [])
  end

  def catch_not_found(e)
    Rails.logger.debug('We had a not found exception.')
    flash.alert = e.to_s
    redirect_to events_path
  end

  def catch_not_found(e)
    Rails.logger.debug('We had a not found exception.')
    flash.alert = e.to_s
    redirect_to events_path
  end
end

app/controllers/members_controller.rb
# frozen_string_literal: true

class MembersController < ApplicationController
    rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found
    before_action :set_member, only: [:show, :edit, :update, :destroy]
    layout 'event_layout'

  # GET /members
  # GET /members.json
  def index
    @members = Member.all
  end

  # GET /members/1
  # GET /members/1.json
  def show; end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/:id/edit
  def edit; end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)
    if @member.save
      flash.notice = 'The member record was created successfully.'
      redirect_to @member
    else
      flash.now.alert = @member.errors.full_messages.to_sentence
      render :new
    end
  end

  # PATCH/PUT /members/id
  # PATCH/PUT /members/1.json
  def update
    if @member.update(member_params)
      flash.notice = 'The member record was updated successfully.'
      redirect_to @member
    else
      flash.now.alert = @member.errors.full_messages.to_sentence
      render :edit
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
      @member.destroy
      respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
      end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_member
    @member = Member.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def member_params
    params.require(:member).permit(:first_name, :last_name, :phone, :birthday, :anniversary)
  end

  def catch_not_found(e)
    Rails.logger.debug('We had a not found exception.')
    flash.alert = e.to_s
    redirect_to members_path
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  layout 'pages_layout'

  def index; end

  def about; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/helpers/members_helper.rb
# frozen_string_literal: true

module MembersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
    <% if event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>
  
        <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>
  
    <div class="field">
      <%= f.label :event_date %>
      <%= f.datetime_select(:event_date, order: [:hour, :month, :day, :year], start_year: 2021) %>
    </div>
  
    <div class="field">
      <%= f.label :event_address %>
      <%= f.text_field :event_location %>
    </div>
  
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

  <br>
  <h1> Attendees </h1>
  <%= form_for(@event) do |f| %>
    <div class="form-group">
        <div class="row">
            <div class="col-md-offset-2 col-md-8">
                <%= f.collection_check_boxes :member_ids, Member.all, :id, :full_name do |cb| %>
                  <% cb.label(class: "checkbox-inline input_checkbox" ) {cb.check_box(class: "checkbox") + cb.text} %>
                <% end %>
            </div>
        </div>
    </div>

    <div class="actions">
        <%= f.submit %>
    </div>
  <% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', event_path(@event) %>

app/views/events/index.html.erb
<div class="container-fluid mb-4 gy-4 p-5 pt-1">

    <div class='row pt-0'>
        <%= link_to 'Members', members_path %>
    </div>

    <div class='row'>
        <h1>Events</h1>
    </div>

    <div class='row'>
        <%= month_calendar(events: @events) do |date, events| %>
            <%= date.day %>
        
            <% events.each do |event| %>
            <div>
            <%= link_to event.description, event_path(id: event.id) %>
            </div>
            <% end %>
        <% end %>
    </div>

    <div class='row pb-1'>
        <%= link_to 'New Event', new_event_path %>
    </div>

</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event Name:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Event Date:</strong>
  <%= @event.event_date %>
</p>

<p>
  <strong>Event Location:</strong>
  <%= @event.event_location %>
</p>

<%= render 'form', event: @event %>

<% if @event.members.any? %>
    <% @members.each do |member| %>
        <p> Member: <%= member.full_name %> </p>
    <% end %>
<% end %>



<%= link_to 'Back', events_path %>
<td><%= link_to 'Edit', edit_event_path(@event) %></td>
<td><%= link_to 'Destroy', @event, method: :delete, data: { confirm: 'Are you sure?' } %></td>

app/views/layouts/_footer.html.erb
<div class="text-center bg-primary text-white row fixed-bottom footnote"> <!-- bg-light is background color & p-5 is padding -->
    <h4 class="m-auto p-2">Attendance. <em>Simplified</em>.</h4>
</div>

app/views/layouts/_navbar.html.erb
<div class='row'>
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand" href="/">EventTrackr</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav text-center" align="right">
          <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>
              <li class='nav-item'>
                  <%= link_to 'Events', events_path, method: :get, class: 'nav-link' %>
              </li>
          <% else %>
              <li class="nav-item">
                  <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                  <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
              </li>
          <% end %>
        </ul>
      </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventAttendance</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="home" data-spy="scroll" data-target=".navbar" data-offset="100">
    <%= render 'layouts/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/event_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventAttendance</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="home" data-spy="scroll" data-target=".navbar" data-offset="100">

    <div class='container-sm bg-light bg-gradient main-div'>

      <%= render 'layouts/navbar' %>

      <div class='row'>
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
      </div>

      <%= yield %>

      <%= render 'layouts/footer' %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>

</html>

app/views/layouts/pages_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventAttendance</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="home" data-spy="scroll" data-target=".navbar" data-offset="100">

    <!--outer div-->

    <div class='container-sm bg-light bg-gradient main-div'>

        <%= render 'layouts/navbar' %>

        <!--image carousel div-->

        <div id="carouselExampleIndicators" class="carousel slide row" data-bs-ride="carousel">

            <!--carousel indicators (at bottom of images)-->

            <div class="carousel-indicators mx-auto">
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to= 0 class="active" aria-current="true" aria-label="Slide 0"></button>

                <% n = 1 %>
                <% 12.times do |n| %>
                    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to= <%= n %>  aria-label="Slide <%= n %>"></button>
                    <% n = n + 1 %>
                <% end %>
            </div>

            <!--carousel images-->

            <div class="carousel-inner carousel-imgs">
                <div class="carousel-item active">
                    <%= image_tag 'cross.jpg', class: "d-block container-lg" %>
                </div>

                <% image_tag_array = [ 'fun-event.jpg', 'church-event-two.jpg', 'bible-study.jpg', 'church-event.jpg',
                                    'class-event.jpg', 'concert-event.jpg', 'event-seating-bw.jpg', 'hand-raised-two.jpg', 'hand-raised.jpg', 'huge-event.jpg', 'network-event.jpg', 'school-event.jpg',
                                    'stem-event.jpg'] %>

                <% image_tag_array.each do |tag| %>
                    <div class="carousel-item">
                        <%= image_tag tag, class: "d-block container-lg" %>
                    </div>
                <% end %>

            </div>

            <!--forward/previous buttons (on side of images)-->

            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                <span class="carousel-control-prev-icon ml-2" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                <span class="carousel-control-next-icon mr-2" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>

        </div>

        <div class='row'>
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
        </div>

        <%= yield %>

        <%= render 'layouts/footer' %>

    </div>          <!--ends outer div-->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_for(member) do |f| %>
    <% if member.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>
  
        <ul>
        <% member.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>
  
    <div class="field">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
  
    <div class="field">
      <%= f.label :phone %>
      <%= f.text_field :phone %>
    </div>
  
    <div class="field">
      <%= f.label :birthday %>
      <%= f.date_select(:birthday, order: [:month, :day] ) %>
    </div>

    <div class="field">
      <%= f.label :anniversary %>
      <%= f.date_select(:anniversary, order: [:month, :day], include_blank: true ) %>
    </div>
  
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
  

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Members</h1>

<table class='text-center'>
  <thead>
    <tr>
      <th>Full Name</th>
      <th>Phone</th>
      <th>Birthday</th>
      <th>Anniversary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%= member.full_name %></td>
        <td><%= member.phone %></td>
        <td><%= member.birthday.strftime('%m-%d') %></td>
        <td><%= member.anniversary.strftime('%m-%d') %></td>
        <td><%= link_to 'Show', member %></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td>
        <td><%= link_to 'Destroy', member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>
<%= link_to 'Back', events_path %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @member.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @member.last_name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @member.phone %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @member.birthday.strftime('%m-%d') %>
</p>

<p>
  <strong>Anniversary:</strong>
  <%= @member.anniversary.strftime('%m-%d') %>
</p>

app/views/pages/about.html.erb
<div id="about" class="container gy-2 p-5 pt-1 mb-5 about-div">

  <div class="row order-lg-1 text-center img-txt text-light mt-0 big-screen-content">
    <h3 class="mb-4">About EventTrackr</h3>
      <p>A website designed with the purpose of streamlining role call for events of all types.</p>
      <p>The built in analytics and reporting functionality will perform the menial calculations for you and free up your time for other tasks.</p>
  </div>

  <!--only visible at (>900px breakpoint)--->

  <div class="row small-screen-content">
    <div class="col-lg order-lg-1 text-center">
      <h3 class="mb-4">About EventTrackr</h3>
        <p>A website designed with the purpose of streamlining role call for events of all types.</p>
        <p>The built in analytics and reporting functionality will perform the menial calculations for you and free up your time for other tasks.</p>
    </div>
  </div>

  <div class='row order-lg-3 mt-2 types-div'>
    <h4 class="mb-4 mt-2 text-center">EventTrackr Supports:</h3>
      <ul class="list-group list-group-flush">
        <% events_array = [ 'Church Events', 'School Functions', 'Networking Conferences', 'Master Classes', 'Zoom Meetings'] %>

        <% events_array.each do |event| %>
          <li class="list-group-item list-group-item-action text-center"><strong><%= event %></strong></li>
        <% end %>
      </ul>
  </div>

</div>

app/views/pages/index.html.erb
<div class="row img-txt gx-7 p-5 pt-1">

  <!--only visible if user is signed in--->

  <% if user_signed_in? %>
    <div class="col-6 d-grid gap-2 order-lg-2 text-center m-auto event-button">
        <a class='btn btn-primary' href='/events'>My Events</a>
    </div>
  <% end %>

  <!--only visible on small/medium screens (<900px)--->

  <div class="row small-screen-content">
    <div class="col-lg order-lg-1 text-center">
      <h3 class="mb-4">About EventTrackr</h3>
        <p>A website designed with the purpose of streamlining role call for events of all types.</p>
        <p>The built in analytics and reporting functionality will perform the menial calculations for you and free up your time for other tasks.</p>
    </div>
  </div>
  
</div>